# Default values for cert-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

certificate:
  enabled: true
  name: tls-cert
  dnsNames:
    - traefik.ddns.net
    - argocd02.ddns.net
letsencrypt: letsencrypt-linhnh
kind: ClusterIssuer
email: linhnh90@gmail.com
server: 'https://acme-v02.api.letsencrypt.org/directory'

