apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  dnsNames: 
    {{- range .Values.certificate.dnsNames }}
    - {{ . |  }}
    {{- end }}
  secretName: {{ .Values.certificate.name }}
  issuerRef: 
    name: {{ .Values.letsencrypt }}
    kind: {{ .Values.kind }}
