---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
spec:
  dnsNames: 
    - traefik03.ddns.net
    - argocd03.ddns.net
    - nginxweb.ddns.net
  secretName: tls-cert
  issuerRef:
    name: letsencrypt-linhnh
    kind: ClusterIssuer