---
kind: ClusterIssuer
apiVersion: cert-manager.io/v1alpha2
metadata:
  name: letsencrypt-linhnh
spec:
  acme:
    email: linhnh90@gmail.com
    privateKeySecretRef:
      name: linhnh90--key
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
      - http01:
          ingress:
            class: traefik
